### ISSUE TITLE
Add Instructor Courses

### ISSUE THREAD

**Issue by GeraAlcantara** [GeraAlcantara/surfLanding#17]
Section Instructor Courses

**Comment by maxiCalderonBuono** [comment]
Yo me encargo

**Comment by GeraAlcantara** [comment]
algún avance en este issue o podemos quitar la asignación y deja que otro lo tome ?

**Comment by maxiCalderonBuono** [comment]
Gera buenos días, perdón por el desorden. Mejor asignemos este issue a otra persona ya que en este momento no puedo encargarme de él. Muchas gracias!

**Comment by leanmarin** [comment]
voy

**Comment by GeraAlcantara** [comment]
[Merge pull request](https://github.com/GeraAlcantara/surfLanding/commit/bfe8865c87adbcd6592c66629072c00eb1f7c54e) https://github.com/GeraAlcantara/surfLanding/pull/45

cerrado con PR
