### ISSUE TITLE
Add Popular Courses

### ISSUE THREAD

**Issue by GeraAlcantara** [GeraAlcantara/surfLanding#18]
Add section Popular courses

**Comment by GeraAlcantara** [comment]
no tabs navigation

**Comment by Franck3017** [comment]
Frances

**Comment by GeraAlcantara** [comment]
algún avance en este issue o podemos quitar la asignación y deja que otro lo tome ?

**Comment by QuesoCaliente** [comment]
yo lo hago :D

**Comment by GeraAlcantara** [comment]
Ok asignado recuerda hacer fork
Nueva branch con el número del issue y hacer la PR 🤟🧀

**Comment by GeraAlcantara** [comment]
close by PR
