### ISSUE TITLE
Customer Say Section

### ISSUE THREAD

**Issue by GeraAlcantara** [GeraAlcantara/surfLanding#19]
Comentarios clientes

**Comment by msarfer** [comment]
Yo puedo intentar esto

**Comment by GeraAlcantara** [comment]
algún avance en este issue o podemos quitar la asignación y deja que otro lo tome ?

**Comment by elobredor** [comment]
Yo me quedo con este

**Comment by manuelurruti** [comment]
Quiero este isue

**Comment by GeraAlcantara** [comment]
[Merge pull request](https://github.com/GeraAlcantara/surfLanding/commit/486f143fe3a0882f299e532b86a4ce3bde84e1f3) https://github.com/GeraAlcantara/surfLanding/pull/44

Close by PR
