### ISSUE TITLE
Add Attribution footer 

### ISSUE THREAD

**Issue by GeraAlcantara** [GeraAlcantara/surfLanding#21]
Agregar atribuciones y redes Mati

**Comment by Martin-Alba** [comment]
Me encargo

**Comment by GeraAlcantara** [comment]
algun avance en este issue o podemos quitar la asignacion y deja que otro lo tome ?

**Comment by Martin-Alba** [comment]
Lo hice pero cuando lo iba a pushear, vi que alguien más lo había hecho entonces no avancé. Calculé que lo iba a terminar el, no recuerdo quien fue

**Comment by GeraAlcantara** [comment]
@Martin-Alba esta era la parte de abajo del footer, la de las redes sociales 

![image](https://user-images.githubusercontent.com/32178037/221669636-5a7f618b-5b2d-4129-9f3c-2a6dbe79c2dd.png)

Pero que apuntaran a las Redes de Matias y que en lugar de design by seria Base on the work of
