### ISSUE TITLE
Menu Navigation enhanced 

### ISSUE THREAD

**Issue by GeraAlcantara** [GeraAlcantara/surfLanding#38]
## Modificar el menu de navegación en mobiles

- El hamburger Menu debe de ser sistemáticamente correcto usando el tag <button>
  - width de 46px por height 46px 
  - reset default styles para botones
  - acomodar la lógica en el JS si es necesario
- Logo de 46px de alto para que sea del acomode con el botón
- justificar between los elementos del flex y hacer el contenedor 100% 
- los link al ser clickeados deben de cerrar el dropdrown del menu 
- mejorar el css del estado cuando los links estan resaltados 

## Modificar Nav 

- verificar estilos de active y aumentar a 2px el border on hover
- Verificar el ::after si esta en uso en el CSS de la navegación

**Comment by imnotseneca** [comment]
Yo puedo encargarme de seguir mejorando la nav-bar!
